stages:
  - build
  - scan

build-and-push:
  image: docker:27.0.3
  stage: build
  services:
    - docker:27.0.3-dind
  before_script:
    - echo "$HARBOR_PASSWORD" | docker login --username "$HARBOR_USERNAME" --password-stdin "$HARBOR_HOST"
  script:
    - docker build -t $HARBOR_HOST/library/$CI_PROJECT_NAME:latest --push .


trivy_scan:
  stage: scan
  image: 
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy image --exit-code 1 --severity HIGH,CRITICAL $HARBOR_HOST/library/$CI_PROJECT_NAME
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH

